"""
Source of truth for the DemoBlaze test case suite.

The spreadsheet is generated from this file rather than hand-maintained, so the
suite is reviewable in a pull request, diffable over time, and impossible to
desync from the automation references it cites. Regenerate with:

    python3 scripts/generate_test_cases.py
"""

# (id, area, title, type, priority, preconditions, steps, data, expected, automation_ref, defect)
# automation_ref = "" means intentionally manual/exploratory — the Summary sheet counts these.

LOGIN = [
    # ---------------- Functional ----------------
    ("LGN-001", "Login modal", "Login modal opens from the header", "Functional", "P1",
     "User is on the home page, logged out",
     "1. Open https://www.demoblaze.com/\n2. Click 'Log in' in the header",
     "-",
     "The 'Log in' modal opens showing Username and Password fields, plus Close and Log in buttons",
     "tests/ui/login/login.spec.ts › logs in with valid credentials", ""),

    ("LGN-002", "Authentication", "Log in with valid credentials", "Functional", "P0",
     "A registered account exists",
     "1. Open the home page\n2. Click 'Log in'\n3. Enter a valid username\n4. Enter the matching password\n5. Click 'Log in'",
     "username: <valid user>\npassword: <valid password>",
     "Modal closes, header shows 'Welcome <username>', 'Log out' is visible and 'Log in' / 'Sign up' are hidden",
     "tests/ui/login/login.spec.ts › logs in with valid credentials", ""),

    ("LGN-003", "Session", "Session persists across page navigation", "Functional", "P0",
     "User is logged in",
     "1. Log in on the home page\n2. Navigate to the Cart page",
     "-",
     "The header still shows 'Welcome <username>' on the Cart page; the session is not lost on navigation",
     "tests/ui/login/login.spec.ts › keeps the session across navigation", ""),

    ("LGN-004", "Session", "Session persists after a page refresh", "Functional", "P1",
     "User is logged in",
     "1. Log in\n2. Press F5 / reload the page",
     "-",
     "User remains logged in after the reload; 'Welcome <username>' is still displayed",
     "tests/ui/login/session.spec.ts › survives a page refresh", ""),

    ("LGN-005", "Session", "Log out returns the user to the anonymous state", "Functional", "P0",
     "User is logged in",
     "1. Click 'Log out' in the header",
     "-",
     "User is redirected to the home page; 'Log in' and 'Sign up' are visible, 'Log out' and the welcome label are hidden",
     "tests/ui/login/login.spec.ts › logs out and returns to the anonymous state", ""),

    ("LGN-006", "Session", "Cart page shows the anonymous state after log out", "Functional", "P1",
     "User was logged in and has logged out",
     "1. Log in\n2. Log out\n3. Navigate to the Cart page",
     "-",
     "The Cart page header shows 'Log in' / 'Sign up' and no welcome label",
     "tests/ui/login/session.spec.ts › shows the anonymous state on the cart page after logging out", ""),

    ("LGN-007", "Login modal", "Login is available from the Cart page", "Functional", "P2",
     "User is logged out",
     "1. Navigate to the Cart page\n2. Click 'Log in'\n3. Submit valid credentials",
     "username: <valid user>\npassword: <valid password>",
     "Login succeeds and the Cart page reflects the authenticated state",
     "", ""),

    ("LGN-008", "Login modal", "Login is available from a product page", "Functional", "P2",
     "User is logged out",
     "1. Open any product page\n2. Click 'Log in'\n3. Submit valid credentials",
     "username: <valid user>\npassword: <valid password>",
     "Login succeeds without leaving the product page context",
     "tests/ui/cart/add-to-cart.spec.ts › does not carry an anonymous cart into the session after login", ""),

    ("LGN-009", "Login modal", "Modal can be dismissed with the Close button", "Functional", "P2",
     "Login modal is open",
     "1. Open the login modal\n2. Click 'Close'",
     "-",
     "Modal closes, the user remains logged out and the page is still interactive",
     "tests/ui/login/login.modal.spec.ts › closes via the footer Close button", ""),

    ("LGN-010", "Login modal", "Modal can be dismissed with the X control", "Functional", "P2",
     "Login modal is open",
     "1. Open the login modal\n2. Click the X in the modal header",
     "-",
     "Modal closes and the user remains logged out",
     "tests/ui/login/login.modal.spec.ts › closes via the header x", ""),

    ("LGN-011", "Login modal", "Modal can be dismissed with the Escape key", "Functional", "P2",
     "Login modal is open",
     "1. Open the login modal\n2. Press Escape",
     "-",
     "Modal closes and the user remains logged out",
     "tests/ui/login/login.modal.spec.ts › closes when Escape is pressed", ""),

    ("LGN-012", "Login modal", "Modal can be dismissed by clicking the backdrop", "Functional", "P2",
     "Login modal is open",
     "1. Open the login modal\n2. Click outside the modal, on the backdrop",
     "-",
     "Modal closes and the user remains logged out",
     "tests/ui/login/login.modal.spec.ts › closes when the backdrop is clicked", ""),

    ("LGN-013", "Login modal", "Re-opened modal does not retain the previous entry", "Edge case", "P1",
     "A user has logged in and then out on the same browser",
     "1. Log in\n2. Log out\n3. Click 'Log in' again",
     "-",
     "Username and password fields are both empty — the previous account's name is not exposed to the next user of the machine",
     "tests/ui/login/login.spec.ts › re-opening the modal after logout starts empty", ""),

    ("LGN-014", "Login modal", "Password input masks the entered value", "Functional", "P1",
     "Login modal is open",
     "1. Type a password into the Password field\n2. Observe the field",
     "password: Passw0rd!QA",
     "Characters are masked (input type=password); the plain value is not visible on screen",
     "tests/ui/login/login.modal.spec.ts › masks the password as it is typed", ""),

    ("LGN-015", "Login modal", "Failed login leaves the modal open for a retry", "Functional", "P1",
     "A registered account exists",
     "1. Open the login modal\n2. Submit a wrong password\n3. Dismiss the alert",
     "username: <valid user>\npassword: wrong-password",
     "The modal remains open with the entered values so the user can correct them without re-opening it",
     "tests/ui/login/login.negative.spec.ts › rejects a wrong password", ""),

    ("LGN-016", "Login modal", "Enter key does not submit the login form", "Edge case", "P2",
     "Login modal is open with valid credentials entered",
     "1. Enter valid credentials\n2. Press Enter instead of clicking 'Log in'",
     "username: <valid user>\npassword: <valid password>",
     "Documented current behaviour: nothing happens — the form has no submit handler bound to Enter. Usability gap, raise as an improvement",
     "", "DEMO-10"),

    ("LGN-017", "Header state", "Welcome label shows the exact username", "Functional", "P2",
     "A registered account exists",
     "1. Log in with a known username",
     "username: pw_a1b2c3d4",
     "Header reads exactly 'Welcome pw_a1b2c3d4' — no truncation, no case change",
     "tests/ui/login/login.spec.ts › logs in with valid credentials", ""),

    ("LGN-018", "Registration", "A new account can be registered", "Functional", "P0",
     "Username is not already taken",
     "1. Click 'Sign up'\n2. Enter a new username and password\n3. Click 'Sign up'",
     "username: <unique>\npassword: Passw0rd!QA",
     "'Sign up successful.' is shown and the account can immediately be used to log in",
     "tests/api/auth.api.spec.ts › registers a new user", ""),

    ("LGN-019", "Registration", "Registering an existing username is rejected", "Negative", "P1",
     "An account already exists",
     "1. Click 'Sign up'\n2. Enter an existing username and any password\n3. Click 'Sign up'",
     "username: <existing user>\npassword: Passw0rd!QA",
     "'This user already exist.' is shown and no second account is created",
     "tests/api/auth.api.spec.ts › rejects a duplicate registration", ""),

    ("LGN-020", "Registration", "Registration with empty fields is blocked", "Negative", "P2",
     "Sign up modal is open",
     "1. Leave username and password empty\n2. Click 'Sign up'",
     "-",
     "'Please fill out Username and Password.' is shown and no request is sent",
     "", ""),

    # ---------------- Negative ----------------
    ("LGN-021", "Authentication", "Wrong password is rejected", "Negative", "P0",
     "A registered account exists",
     "1. Open the login modal\n2. Enter a valid username and an incorrect password\n3. Click 'Log in'",
     "username: <valid user>\npassword: definitely-wrong",
     "'Wrong password.' is shown and the user remains logged out",
     "tests/ui/login/login.negative.spec.ts › rejects a wrong password", ""),

    ("LGN-022", "Authentication", "Unknown username is rejected", "Negative", "P0",
     "The username does not exist",
     "1. Open the login modal\n2. Enter a username that was never registered\n3. Click 'Log in'",
     "username: ghost_9f2a1c\npassword: Passw0rd!QA",
     "'User does not exist.' is shown and the user remains logged out",
     "tests/ui/login/login.negative.spec.ts › rejects an unknown username", ""),

    ("LGN-023", "Validation", "Both fields empty is blocked client-side", "Negative", "P1",
     "Login modal is open",
     "1. Leave both fields empty\n2. Click 'Log in'",
     "-",
     "'Please fill out Username and Password.' is shown; no login request reaches the API",
     "tests/ui/login/login.negative.spec.ts › blocks submission when both fields are empty", ""),

    ("LGN-024", "Validation", "Empty password is blocked", "Negative", "P1",
     "A registered account exists",
     "1. Enter a valid username\n2. Leave the password empty\n3. Click 'Log in'",
     "username: <valid user>\npassword: (empty)",
     "'Please fill out Username and Password.' is shown and the user remains logged out",
     "tests/ui/login/login.negative.spec.ts › blocks submission when only the password is missing", ""),

    ("LGN-025", "Validation", "Empty username is blocked in the UI", "Negative", "P1",
     "Login modal is open",
     "1. Leave the username empty\n2. Enter any password\n3. Click 'Log in'",
     "username: (empty)\npassword: Passw0rd!QA",
     "'Please fill out Username and Password.' is shown. Note the API itself returns HTTP 500 for this input (DEMO-2) — the UI guard is the only thing preventing it",
     "tests/api/auth.api.spec.ts › rejects a login with an empty username", "DEMO-2"),

    ("LGN-026", "Validation", "Whitespace-only username is not treated as empty", "Edge case", "P2",
     "Login modal is open",
     "1. Enter spaces only as the username\n2. Enter a valid password\n3. Click 'Log in'",
     "username: '   '\npassword: Passw0rd!QA",
     "The client-side guard checks for an empty string only, so the request is sent and 'User does not exist.' is returned",
     "tests/api/auth.api.spec.ts › does not trim a whitespace-padded username", ""),

    ("LGN-027", "Authentication", "Username is case-sensitive", "Edge case", "P1",
     "A registered lowercase account exists",
     "1. Enter the username in UPPERCASE\n2. Enter the correct password\n3. Click 'Log in'",
     "username: PW_A1B2C3D4\npassword: <valid password>",
     "'User does not exist.' — usernames are matched case-sensitively",
     "tests/ui/login/login.negative.spec.ts › treats the username as case-sensitive", ""),

    ("LGN-028", "Authentication", "Password is case-sensitive", "Edge case", "P1",
     "A registered account exists",
     "1. Enter a valid username\n2. Enter the password with inverted case\n3. Click 'Log in'",
     "username: <valid user>\npassword: pASSW0RD!qa",
     "'Wrong password.' — passwords are matched case-sensitively",
     "tests/api/auth.api.spec.ts › treats the password as case-sensitive", ""),

    ("LGN-029", "Authentication", "Surrounding whitespace in the username is not trimmed", "Edge case", "P2",
     "A registered account exists",
     "1. Enter the valid username padded with leading and trailing spaces\n2. Enter the correct password\n3. Click 'Log in'",
     "username: '  pw_a1b2c3d4  '\npassword: <valid password>",
     "'User does not exist.' — the input is not trimmed. Pinned as current behaviour so a future change is a deliberate decision",
     "tests/ui/login/login.negative.spec.ts › does not trim surrounding whitespace in the username", ""),

    ("LGN-030", "Authentication", "Valid username with another account's password is rejected", "Negative", "P1",
     "Two registered accounts exist",
     "1. Enter user A's username\n2. Enter user B's password\n3. Click 'Log in'",
     "username: <user A>\npassword: <user B password>",
     "'Wrong password.' and no session is created for either account",
     "tests/api/auth.api.spec.ts › rejects a valid username paired with another account's password", ""),

    ("LGN-031", "Security", "Error wording reveals whether an account exists", "Security", "P2",
     "One registered account exists and one username does not",
     "1. Attempt login with a valid username and wrong password\n2. Attempt login with a username that does not exist",
     "case 1: <valid user> / wrong\ncase 2: ghost_9f2a1c / any",
     "The two attempts return different messages ('Wrong password.' vs 'User does not exist.'), which allows username enumeration. Raised as DEMO-5; expected behaviour is a single generic message",
     "tests/ui/login/login.negative.spec.ts › does not leak whether an account exists through timing or wording", "DEMO-5"),

    ("LGN-032", "Security", "Repeated failed logins are not rate-limited or locked out", "Security", "P1",
     "A registered account exists",
     "1. Submit an incorrect password 20 times in a row",
     "username: <valid user>\npassword: wrong-<n>",
     "All 20 attempts are processed with no lockout, delay, CAPTCHA or rate limit — the account is open to brute force. Raise as a finding",
     "tests/api/auth.api.spec.ts › applies no rate limit or lockout to repeated failures", "DEMO-11"),

    ("LGN-033", "Security", "SQL injection payload in the username is handled as literal text", "Security", "P1",
     "Login modal is open",
     "1. Enter a SQL injection payload as the username\n2. Enter any password\n3. Click 'Log in'",
     "username: ' OR '1'='1\npassword: anything",
     "The attempt is rejected and no session is created; no authentication bypass, no server error, no SQL error text surfaced. Note the rejection wording is not asserted: DemoBlaze is a public sandbox and this username is already registered by another tester, so the message depends on state the suite does not own",
     "tests/ui/login/login.modal.spec.ts › treats a SQL injection payload as literal text", ""),

    ("LGN-034", "Security", "XSS payload in the username is not executed", "Security", "P1",
     "Login modal is open",
     "1. Enter a script payload as the username\n2. Submit\n3. Observe the alert and the page",
     "username: <script>alert(1)</script>\npassword: anything",
     "The payload is treated as text; no script executes (its own alert never fires) and nothing is rendered as HTML in the error message or the welcome label. The rejection wording is not asserted — this username is already registered on the shared sandbox",
     "tests/ui/login/login.modal.spec.ts › does not execute a script payload in the username", ""),

    ("LGN-035", "Boundary", "Very long username is handled without a crash", "Edge case", "P2",
     "Login modal is open",
     "1. Enter a 256-character username\n2. Enter any password\n3. Click 'Log in'",
     "username: 'A' x 256\npassword: Passw0rd!QA",
     "The request is handled gracefully — a normal rejection, no 500 and no unhandled client error. The rejection wording is not asserted, since this username already exists on the shared sandbox",
     "tests/ui/login/login.modal.spec.ts › handles a very long username without breaking", ""),

    ("LGN-036", "Boundary", "Single-character credentials are accepted for registration and login", "Edge case", "P2",
     "Username is available",
     "1. Register with a 1-character username and 1-character password\n2. Log in with them",
     "username: a\npassword: b",
     "Documented behaviour: there is no minimum length policy. Flag the absence of a password policy as a finding",
     "tests/api/auth.api.spec.ts › accepts single-character credentials — no password policy", "DEMO-12"),

    ("LGN-037", "Internationalisation", "Unicode username round-trips correctly", "Edge case", "P2",
     "Username is available",
     "1. Register with a Unicode username\n2. Log in with it\n3. Observe the welcome label",
     "username: nguyễn_山田\npassword: Passw0rd!QA",
     "Registration and login succeed and the welcome label renders the username without mojibake",
     "tests/api/auth.api.spec.ts › round-trips a unicode username", ""),

    ("LGN-038", "Boundary", "Password containing special characters works", "Edge case", "P2",
     "Username is available",
     "1. Register with a password of special characters\n2. Log in with it",
     "password: !@#$%^&*()_+{}|:\"<>?",
     "Registration and login both succeed — base64 encoding of the password does not corrupt the value",
     "tests/api/auth.api.spec.ts › accepts a password of special characters", ""),

    # ---------------- Edge / session ----------------
    ("LGN-039", "Session", "Clearing the session cookie logs the user out", "Edge case", "P2",
     "User is logged in",
     "1. Log in\n2. Delete the 'tokenp_' cookie via devtools\n3. Reload the page",
     "-",
     "The page renders in the anonymous state; no stale authenticated UI is shown",
     "tests/ui/login/session.spec.ts › ends when the session cookie is cleared", ""),

    ("LGN-040", "Session", "Malformed auth token is rejected", "Negative", "P1",
     "User is logged in",
     "1. Log in\n2. Overwrite 'tokenp_' with a malformed value\n3. Open the Cart page",
     "tokenp_: not-a-real-token",
     "The app reports the bad token rather than exposing another user's data; no cart contents are rendered",
     "tests/ui/login/session.spec.ts › a malformed auth token does not expose cart data", ""),

    ("LGN-041", "Session", "Browser back after logout does not restore the session", "Edge case", "P1",
     "User has logged in then out",
     "1. Log in\n2. Log out\n3. Press the browser Back button",
     "-",
     "The restored page shows the anonymous state, not a cached authenticated header",
     "tests/ui/login/session.spec.ts › is not restored by the browser back button after logout", ""),

    ("LGN-042", "Session", "The same account can be used in two browsers at once", "Edge case", "P2",
     "A registered account exists",
     "1. Log in as the account in browser A\n2. Log in as the same account in browser B\n3. Act in both",
     "-",
     "Both sessions remain valid and observe the same server-side cart; neither session invalidates the other",
     "tests/ui/login/session.spec.ts › supports the same account in two independent browser sessions", ""),

    ("LGN-043", "Resilience", "Login failure when the API is unreachable is communicated", "Negative", "P1",
     "Login modal is open",
     "1. Block requests to api.demoblaze.com\n2. Submit valid credentials",
     "username: <valid user>\npassword: <valid password>",
     "Expected: the user sees an error. Actual: the request fails silently with no feedback and the modal simply stays open. Raise as a finding",
     "tests/ui/login/session.spec.ts › login failure is silent when the API is unreachable", "DEMO-13"),

    ("LGN-044", "API", "Authentication failures are returned with HTTP 200", "Negative", "P1",
     "-",
     "1. POST /login with a username that does not exist\n2. Inspect the HTTP status and body",
     "{username: 'ghost_x', password: '<base64>'}",
     "Status is 200 with {errorMessage: 'User does not exist.'}. Pinned so any client relying on status codes is known to be at risk",
     "tests/api/auth.api.spec.ts › reports authentication failures at HTTP 200", ""),
]

CART = [
    # ---------------- Add to cart ----------------
    ("CRT-001", "Add to cart", "Add a single product to the cart", "Functional", "P0",
     "User is logged in",
     "1. Open a product page\n2. Click 'Add to cart'\n3. Accept the confirmation alert\n4. Open the Cart page",
     "product: Samsung galaxy s6",
     "'Product added.' is shown, and the Cart page lists one line for the product",
     "tests/ui/cart/add-to-cart.spec.ts › adds a product to the cart and shows it with the right price", ""),

    ("CRT-002", "Add to cart", "Cart line price matches the product page price", "Functional", "P0",
     "User is logged in",
     "1. Note the price on the product page\n2. Add the product to the cart\n3. Open the Cart page",
     "product: Samsung galaxy s6 ($360)",
     "The cart line price equals the price shown on the product page and the value returned by the API",
     "tests/ui/cart/add-to-cart.spec.ts › adds a product to the cart and shows it with the right price", ""),

    ("CRT-003", "Add to cart", "Multiple different products can be added", "Functional", "P0",
     "User is logged in with an empty cart",
     "1. Add a phone\n2. Add a laptop\n3. Add a monitor\n4. Open the Cart page",
     "Samsung galaxy s6, Sony vaio i5, Apple monitor 24",
     "The cart contains exactly three lines, one per product, each with the correct title and price",
     "tests/ui/cart/add-to-cart.spec.ts › sums multiple different products into the displayed total", ""),

    ("CRT-004", "Totals", "Cart total equals the sum of the line prices", "Functional", "P0",
     "Cart contains several products",
     "1. Add three products\n2. Open the Cart page\n3. Compare the total against the sum of the visible lines",
     "360 + 790 + 400",
     "The displayed total equals 1550 and equals the arithmetic sum of the lines shown to the customer",
     "tests/ui/cart/add-to-cart.spec.ts › sums multiple different products into the displayed total", ""),

    ("CRT-005", "Add to cart", "The same product can be added twice", "Edge case", "P1",
     "User is logged in with an empty cart",
     "1. Add the same product twice\n2. Open the Cart page",
     "product: Samsung galaxy s6 x2",
     "Two separate lines are shown (there is no quantity column) and the total is double the unit price",
     "tests/ui/cart/add-to-cart.spec.ts › allows the same product to be added twice as two lines", ""),

    ("CRT-006", "Add to cart", "Products from every category can be added", "Functional", "P1",
     "User is logged in",
     "1. Filter by Phones and add a product\n2. Filter by Laptops and add a product\n3. Filter by Monitors and add a product",
     "one product per category",
     "All three are added successfully; category filtering does not affect the add-to-cart flow",
     "tests/ui/cart/add-to-cart.spec.ts › a product from every category can be added", ""),

    ("CRT-007", "Add to cart", "Confirmation wording differs when logged out", "Edge case", "P2",
     "User is logged out",
     "1. Open a product page while logged out\n2. Click 'Add to cart'",
     "product: Samsung galaxy s6",
     "The alert reads 'Product added' with no full stop, unlike the logged-in path's 'Product added.'. Inconsistent copy from two code paths — DEMO-9",
     "tests/ui/cart/add-to-cart.spec.ts › does not carry an anonymous cart into the session after login", "DEMO-9"),

    ("CRT-008", "Add to cart", "An anonymous cart is not merged on login", "Edge case", "P1",
     "User is logged out",
     "1. Add a product while logged out\n2. Log in with a registered account\n3. Open the Cart page",
     "product: Samsung galaxy s6",
     "The cart is empty — items added anonymously are silently discarded rather than merged into the account. Raised as DEMO-6",
     "tests/ui/cart/add-to-cart.spec.ts › does not carry an anonymous cart into the session after login", "DEMO-6"),

    ("CRT-009", "Add to cart", "Add to cart remains usable after a successful add", "Functional", "P2",
     "User is logged in on a product page",
     "1. Add the product\n2. Dismiss the alert\n3. Observe the button",
     "-",
     "The 'Add to cart' link stays enabled and the page does not navigate away",
     "tests/ui/cart/add-to-cart.spec.ts › the add-to-cart control stays usable after a successful add", ""),

    ("CRT-010", "Catalogue", "Product page price matches the catalogue listing", "Functional", "P1",
     "-",
     "1. Note the price on a catalogue card\n2. Open that product's page",
     "product: Samsung galaxy s6",
     "Both views show the same price — no disagreement between the list and detail sources",
     "tests/api/catalog.api.spec.ts › single-product view agrees with the list view", ""),

    # ---------------- Cart view & management ----------------
    ("CRT-011", "Cart view", "A new account starts with an empty cart", "Functional", "P1",
     "A newly registered account, logged in",
     "1. Register a new account\n2. Log in\n3. Open the Cart page",
     "-",
     "No product lines are shown and the total is blank/zero",
     "tests/ui/cart/add-to-cart.spec.ts › shows an empty cart for a brand-new account", ""),

    ("CRT-012", "Cart view", "Empty cart renders without errors", "Edge case", "P2",
     "User is logged in with an empty cart",
     "1. Open the Cart page",
     "-",
     "The table renders with headers only, the total is empty, 'Place Order' is present, and no console errors are raised",
     "tests/ui/cart/add-to-cart.spec.ts › shows an empty cart for a brand-new account", ""),

    ("CRT-013", "Cart management", "Deleting a line removes it and recalculates the total", "Functional", "P0",
     "Cart contains two products",
     "1. Open the Cart page\n2. Click 'Delete' on the first line",
     "phone $360 + laptop $790",
     "The deleted line disappears, the remaining line is intact, and the total drops to 790",
     "tests/ui/cart/add-to-cart.spec.ts › removes a line and recalculates the total", ""),

    ("CRT-014", "Cart management", "Deleting the last line empties the cart", "Edge case", "P1",
     "Cart contains exactly one product",
     "1. Open the Cart page\n2. Delete the only line",
     "product: Apple monitor 24",
     "The cart shows no lines and the total returns to zero/blank",
     "tests/ui/cart/add-to-cart.spec.ts › empties to a zero total when the last line is removed", ""),

    ("CRT-015", "Cart management", "Deleting one duplicate line leaves the other", "Edge case", "P1",
     "Cart contains the same product twice",
     "1. Open the Cart page\n2. Delete one of the two identical lines",
     "product: Samsung galaxy s6 x2",
     "Exactly one line remains and the total equals a single unit price — lines are addressed individually, not by product",
     "tests/api/cart.api.spec.ts › keeps each line addressable by its own id", ""),

    ("CRT-016", "Persistence", "Cart survives a page reload", "Functional", "P1",
     "Cart contains a product",
     "1. Open the Cart page\n2. Reload the page",
     "product: Samsung galaxy s6",
     "The same line is still present after the reload — the cart is server-side, not browser state",
     "tests/ui/cart/add-to-cart.spec.ts › persists the cart across a page reload", ""),

    ("CRT-017", "Persistence", "Cart survives logging out and back in", "Functional", "P1",
     "Cart contains a product and the user is logged in",
     "1. Add a product\n2. Log out\n3. Log back in with the same account\n4. Open the Cart page",
     "product: Samsung galaxy s6",
     "The cart still contains the product; it is bound to the account rather than the session",
     "tests/ui/cart/add-to-cart.spec.ts › cart survives logging out and back in", ""),

    ("CRT-018", "Isolation", "Carts are isolated between accounts", "Security", "P0",
     "Two registered accounts exist",
     "1. Log in as user A and add a product\n2. Log in as user B in a clean session\n3. Open the Cart page",
     "user A: 1 product\nuser B: new account",
     "User B's cart is empty and user A's cart is unchanged — no cross-account leakage",
     "tests/api/cart.api.spec.ts › carts are isolated between accounts", ""),

    ("CRT-019", "Cart view", "Cart contents match the API's view of the cart", "Functional", "P1",
     "Cart contains several products",
     "1. Add three products\n2. Open the Cart page\n3. Call POST /viewcart with the same token",
     "-",
     "The rendered lines and the API response describe the same set of items — the UI does not hide or invent lines",
     "tests/api/cart.api.spec.ts › adds an item and reads it back", ""),

    ("CRT-020", "Cart view", "Each cart line renders its product image and title", "UI", "P2",
     "Cart contains a product",
     "1. Open the Cart page\n2. Inspect the line",
     "product: Samsung galaxy s6",
     "The image loads (no broken image) and the title matches the product exactly",
     "tests/ui/cart/add-to-cart.spec.ts › each cart line renders its product image", ""),

    ("CRT-021", "Cart management", "Deleting an item that no longer exists is harmless", "Edge case", "P2",
     "User is logged in",
     "1. Call POST /deleteitem with an id that is not in any cart",
     "id: pw-nonexistent",
     "The API returns success and no cart is modified — the operation is idempotent",
     "tests/api/cart.api.spec.ts › deleting a non-existent line item is a no-op, not an error", ""),

    ("CRT-022", "Cart management", "Cart can be emptied line by line", "Functional", "P2",
     "Cart contains three products",
     "1. Delete each line in turn\n2. Observe the total after each deletion",
     "three products",
     "The total decreases by the corresponding line price after each deletion and reaches zero when the cart is empty",
     "tests/api/cart.api.spec.ts › empties the cart", ""),

    # ---------------- Checkout ----------------
    ("CRT-023", "Checkout", "Place Order modal opens and shows the total", "Functional", "P0",
     "Cart contains products",
     "1. Open the Cart page\n2. Click 'Place Order'",
     "phone $360 + laptop $790",
     "The order modal opens showing 'Total: 1150' and the Name, Country, City, Credit card, Month, Year fields",
     "tests/ui/cart/place-order.spec.ts › completes an order and reports the correct receipt", ""),

    ("CRT-024", "Checkout", "Order modal total matches the cart total", "Functional", "P0",
     "Cart contains products",
     "1. Note the cart total\n2. Open the order modal",
     "phone $360 + laptop $790",
     "Both show the same figure — the customer is never shown two different amounts",
     "tests/ui/cart/place-order.spec.ts › completes an order and reports the correct receipt", ""),

    ("CRT-025", "Checkout", "Place an order with complete, valid details", "Functional", "P0",
     "Cart contains products and the user is logged in",
     "1. Open the order modal\n2. Fill Name, Country, City, Credit card, Month, Year\n3. Click 'Purchase'",
     "Jane Tester / Vietnam / Ho Chi Minh City / 4111111111111111 / 12 / 2030",
     "A confirmation appears titled 'Thank you for your purchase!' with the order id, amount, card number, name and date",
     "tests/ui/cart/place-order.spec.ts › completes an order and reports the correct receipt", ""),

    ("CRT-026", "Checkout", "Receipt amount equals the cart total", "Functional", "P0",
     "Cart total is known",
     "1. Place a valid order\n2. Read the Amount line on the receipt",
     "cart total: 1150",
     "The receipt reads 'Amount: 1150 USD' — the charged amount matches what the customer agreed to",
     "tests/ui/cart/place-order.spec.ts › completes an order and reports the correct receipt", ""),

    ("CRT-027", "Checkout", "Receipt echoes the submitted card number and name", "Functional", "P1",
     "Order modal completed with known values",
     "1. Place a valid order\n2. Compare the receipt fields with the submitted values",
     "card: 4111111111111111\nname: Jane Tester",
     "Both values appear on the receipt exactly as entered. Note the full PAN is displayed unmasked — raise as a privacy finding",
     "tests/ui/cart/place-order.spec.ts › completes an order and reports the correct receipt", "DEMO-14"),

    ("CRT-028", "Checkout", "Receipt carries a numeric order id", "Functional", "P2",
     "-",
     "1. Place a valid order\n2. Read the Id line",
     "-",
     "The id is a non-empty numeric value the customer could quote to support",
     "tests/ui/cart/place-order.spec.ts › completes an order and reports the correct receipt", ""),

    ("CRT-029", "Checkout", "Cart is emptied after a successful order (UI)", "Functional", "P0",
     "Cart contains a product",
     "1. Place a valid order\n2. Confirm the receipt\n3. Open the Cart page",
     "product: Apple monitor 24",
     "The cart is empty — the ordered goods are not left available to be ordered again",
     "tests/ui/cart/place-order.spec.ts › empties the cart in the UI after a completed order", ""),

    ("CRT-030", "Checkout", "Cart is emptied after a successful order (server state)", "Functional", "P0",
     "Cart contains products",
     "1. Place a valid order\n2. Call POST /viewcart with the same token",
     "-",
     "The API reports an empty cart — the state is genuinely cleared, not just hidden in the UI",
     "tests/ui/cart/place-order.spec.ts › completes an order and reports the correct receipt", ""),

    ("CRT-031", "Checkout", "Confirming the receipt returns the user to the catalogue", "Functional", "P2",
     "A receipt is displayed",
     "1. Click 'OK' on the receipt",
     "-",
     "The browser navigates to the home page",
     "tests/ui/cart/place-order.spec.ts › completes an order and reports the correct receipt", ""),

    ("CRT-032", "Checkout", "Closing the order modal does not place an order", "Functional", "P1",
     "Cart contains a product",
     "1. Open the order modal\n2. Fill in the fields\n3. Click 'Close' instead of 'Purchase'\n4. Re-open the Cart page",
     "valid details",
     "No receipt is shown and the cart still contains the product",
     "tests/ui/cart/place-order.spec.ts › closing the order modal does not place an order", ""),

    ("CRT-033", "Validation", "Order without a name is rejected", "Negative", "P0",
     "Cart contains a product",
     "1. Open the order modal\n2. Leave Name empty, fill the rest\n3. Click 'Purchase'",
     "name: (empty)\ncard: 4111111111111111",
     "'Please fill out Name and Creditcard.' is shown, no receipt appears, and the cart is untouched",
     "tests/ui/cart/place-order.spec.ts › rejects an order with no name", ""),

    ("CRT-034", "Validation", "Order without a credit card is rejected", "Negative", "P0",
     "Cart contains a product",
     "1. Open the order modal\n2. Leave Credit card empty, fill the rest\n3. Click 'Purchase'",
     "name: Jane Tester\ncard: (empty)",
     "'Please fill out Name and Creditcard.' is shown, no receipt appears, and the cart is untouched",
     "tests/ui/cart/place-order.spec.ts › rejects an order with no credit card", ""),

    ("CRT-035", "Validation", "Order with both required fields empty is rejected", "Negative", "P1",
     "Cart contains a product",
     "1. Open the order modal\n2. Click 'Purchase' with an empty form",
     "-",
     "'Please fill out Name and Creditcard.' is shown and no order is created",
     "tests/ui/cart/place-order.spec.ts › rejects an order with both required fields empty", ""),

    ("CRT-036", "Validation", "Country, City, Month and Year are not mandatory", "Edge case", "P2",
     "Cart contains a product",
     "1. Fill only Name and Credit card\n2. Click 'Purchase'",
     "name: Jane Tester\ncard: 4111111111111111",
     "The order completes. Documented behaviour: only two of the six fields are validated at all",
     "tests/ui/cart/place-order.spec.ts › completes an order and reports the correct receipt", ""),

    ("CRT-037", "Validation", "Whitespace-only name is accepted", "Edge case", "P1",
     "Cart contains a product",
     "1. Enter spaces only in Name\n2. Enter a valid card\n3. Click 'Purchase'",
     "name: '   '\ncard: 4111111111111111",
     "The order completes — validation checks for an empty string, not for meaningful input. Raised as DEMO-4",
     "tests/ui/cart/place-order.spec.ts › accepts a whitespace-only name — validation is presence-only", "DEMO-4"),

    ("CRT-038", "Validation", "Non-numeric credit card is accepted", "Negative", "P1",
     "Cart contains a product",
     "1. Enter a valid name\n2. Enter letters in the Credit card field\n3. Click 'Purchase'",
     "card: not-a-card-number",
     "The order completes with the text echoed on the receipt — there is no card format or Luhn validation. Raised as DEMO-4",
     "tests/ui/cart/place-order.spec.ts › accepts a non-numeric credit card — no format validation", "DEMO-4"),

    ("CRT-039", "Validation", "An empty cart can be checked out for zero", "Negative", "P0",
     "User is logged in with an empty cart",
     "1. Open the Cart page with no items\n2. Click 'Place Order'\n3. Fill Name and Credit card\n4. Click 'Purchase'",
     "name: Jane Tester\ncard: 4111111111111111",
     "Expected: checkout is blocked for an empty cart. Actual: a receipt is issued for 'Amount: 0 USD' with a real order id. Raised as DEMO-3",
     "tests/ui/cart/place-order.spec.ts › accepts an order for an empty cart at zero value", "DEMO-3"),

    ("CRT-040", "Validation", "Invalid expiry month and year are accepted", "Edge case", "P2",
     "Cart contains a product",
     "1. Enter month 13 and a year in the past\n2. Complete the remaining required fields\n3. Click 'Purchase'",
     "month: 13\nyear: 1999",
     "The order completes — expiry values are neither range-checked nor compared against the current date",
     "", ""),

    ("CRT-041", "Internationalisation", "Unicode customer name is preserved on the receipt", "Edge case", "P2",
     "Cart contains a product",
     "1. Enter a Unicode name\n2. Complete the order",
     "name: Nguyễn Văn Ánh 山田太郎",
     "The receipt shows the name exactly as entered, with no mojibake or stripped characters",
     "tests/ui/cart/place-order.spec.ts › preserves unicode characters in the customer name", ""),

    ("CRT-042", "Boundary", "Very long customer name is handled", "Edge case", "P2",
     "Cart contains a product",
     "1. Enter a 256-character name\n2. Complete the order",
     "name: 'A' x 256",
     "The order completes and the receipt renders without breaking the dialog layout",
     "tests/ui/cart/place-order.spec.ts › handles a very long customer name", ""),

    ("CRT-043", "Security", "XSS payload in the name is not executed on the receipt", "Security", "P1",
     "Cart contains a product",
     "1. Enter a script payload as the Name\n2. Complete the order\n3. Observe the receipt",
     "name: <img src=x onerror=alert(1)>",
     "The payload is rendered as text; no script executes and no element is injected into the receipt",
     "tests/ui/cart/place-order.spec.ts › does not execute a script payload in the customer name", ""),

    ("CRT-044", "Checkout", "Receipt date shows the correct calendar month", "Functional", "P1",
     "Cart contains a product",
     "1. Place a valid order on a known date\n2. Read the Date line on the receipt",
     "order placed 04/09/2026",
     "Expected 'Date: 4/9/2026'. Actual '4/8/2026' — the month is one behind because the app uses a zero-indexed getMonth(). Raised as DEMO-1",
     "tests/ui/cart/place-order.spec.ts › receipt shows the correct calendar month @bug", "DEMO-1"),

    ("CRT-045", "Checkout", "Checkout is possible while logged out", "Edge case", "P1",
     "User is logged out with an anonymous cart",
     "1. Add a product while logged out\n2. Open the Cart page\n3. Complete the order form and purchase",
     "name: Jane Tester\ncard: 4111111111111111",
     "Documented behaviour: an anonymous purchase is accepted with no account. Confirm this is intended for the business, since the order cannot be tied to a customer",
     "", ""),

    ("CRT-046", "Checkout", "Double-clicking Purchase does not create two orders", "Edge case", "P1",
     "Order modal is complete",
     "1. Fill the order form\n2. Double-click 'Purchase' rapidly",
     "valid details",
     "Only one confirmation and one order id result; the cart is cleared once",
     "", ""),

    ("CRT-047", "Checkout", "Card number with spaces or dashes is handled", "Edge case", "P2",
     "Cart contains a product",
     "1. Enter a card number containing spaces and dashes\n2. Complete the order",
     "card: 4111-1111 1111-1111",
     "The order completes and the receipt echoes the value as entered — no normalisation is applied",
     "tests/ui/cart/place-order.spec.ts › accepts a card number containing spaces and dashes", ""),

    ("CRT-048", "Resilience", "Checkout when the API is unreachable", "Negative", "P1",
     "Cart contains a product",
     "1. Block requests to api.demoblaze.com\n2. Complete and submit the order form",
     "valid details",
     "Expected: the customer is told the order failed. Actual: the confirmation is shown regardless because it is rendered client-side before the server responds. Raise as a finding",
     "tests/ui/cart/place-order.spec.ts › does not confirm an order the server never received", "DEMO-15"),

    ("CRT-049", "Catalogue", "Category filters return only that category", "Functional", "P2",
     "-",
     "1. Click Phones, then Laptops, then Monitors\n2. Inspect the returned products",
     "categories: phone, notebook, monitor",
     "Runs once per category. Each filter returns a non-empty set and no product from another category leaks in. Note the three category links share id='itemc' (DEMO-7), so they must be selected by role and text",
     "tests/api/catalog.api.spec.ts › filters by category \"phone\" without leaking other categories", "DEMO-7"),

    ("CRT-050", "Catalogue", "The catalogue listing endpoint is paginated", "Edge case", "P2",
     "-",
     "1. Call GET /entries\n2. Compare against the union of the three category queries",
     "-",
     "/entries returns only the first 9 of 15 products. Any test or client that treats it as the whole catalogue will miss every monitor — documented in docs/api-contract.md. One title also carries a trailing newline (DEMO-8), so title comparisons must be trimmed",
     "tests/api/catalog.api.spec.ts › returns a non-empty product list", "DEMO-8"),

    ("CRT-060", "End-to-end", "Complete purchase journey from registration to receipt", "Functional", "P0",
     "No account exists; user is a first-time visitor",
     "1. Open the home page\n2. Register a new account via 'Sign up'\n3. Log in with those credentials\n4. Filter by a category\n5. Open a product and check its title and price\n6. Add it to the cart\n7. Open the cart and check the line and total\n8. Place the order with valid details\n9. Confirm the receipt\n10. Re-open the cart",
     "new account + Samsung galaxy s6 + valid order details",
     "Every step succeeds and state carries between them: the account can log in, the product page matches the catalogue, the cart total matches the price, the receipt amount matches the cart, and the cart is empty afterwards both in the UI and on the server",
     "tests/ui/cart/journey.spec.ts › register, log in, add to cart and buy", ""),

    ("CRT-061", "Boundary", "A large cart totals correctly and renders every line", "Edge case", "P1",
     "User is logged in with an empty cart",
     "1. Add 10 different products\n2. Open the Cart page\n3. Compare the total against the sum of the visible lines",
     "10 distinct products",
     "All 10 lines render and the displayed total equals the arithmetic sum of the lines. Guards the class of bug that works for two items and drifts at scale — string concatenation instead of addition, partial re-render, paginated fetch",
     "tests/ui/cart/add-to-cart.spec.ts › totals a large cart correctly", ""),

    ("CRT-062", "Boundary", "Cheapest and most expensive products total correctly", "Edge case", "P2",
     "User is logged in with an empty cart",
     "1. Resolve the cheapest and most expensive products from the catalogue at runtime\n2. Add both\n3. Open the Cart page",
     "price extremes, resolved at runtime",
     "The total equals the sum of the two prices — the widest spread the real catalogue allows, with no rounding or truncation",
     "tests/ui/cart/add-to-cart.spec.ts › totals the cheapest and most expensive products correctly", ""),

    ("CRT-063", "Persistence", "Cart survives into a completely fresh browser session", "Edge case", "P1",
     "An account with an item in its cart",
     "1. Add a product while logged in\n2. Open a brand-new browser session (new context, no cookies)\n3. Log in with the same account\n4. Open the Cart page",
     "same account, clean browser profile",
     "The product is still in the cart. Distinct from a reload, which keeps the context and its memory — this proves the cart is genuinely server-side state, as a returning customer on a new day would experience",
     "tests/ui/cart/add-to-cart.spec.ts › cart survives into a completely fresh browser session", ""),

    # ---------------- Negative: invalid input, auth failures, error handling ----------------
    ("CRT-051", "Error handling", "Malformed auth token is rejected when adding to the cart", "Negative", "P1",
     "User has a session",
     "1. Replace the 'tokenp_' cookie with a malformed value\n2. Open a product page\n3. Click 'Add to cart'",
     "tokenp_: not-a-real-token",
     "The API returns {errorMessage: 'Bad parameter, token malformed.'} and the app surfaces it. Nothing is added to any cart",
     "tests/api/cart.api.spec.ts › rejects a malformed auth token when adding to the cart", ""),

    ("CRT-052", "Error handling", "Malformed auth token is rejected when reading the cart", "Negative", "P1",
     "User has a session",
     "1. Replace the 'tokenp_' cookie with a malformed value\n2. Open the Cart page",
     "tokenp_: not-a-real-token",
     "'Bad parameter, token malformed.' is returned and no cart contents are rendered — no other account's data is exposed",
     "tests/api/cart.api.spec.ts › rejects a malformed auth token when reading the cart", ""),

    ("CRT-053", "Auth failure", "Expired token is reported and the user is asked to log in again", "Negative", "P1",
     "A session whose token has expired",
     "1. Wait for / force token expiry\n2. Attempt to add a product to the cart",
     "expired tokenp_",
     "The app shows 'Your token has expired, please login again.' and the item is not added. This branch exists in the app's client code but cannot be triggered on demand without a way to expire a token",
     "", ""),

    ("CRT-054", "Auth failure", "One account cannot delete another account's cart line", "Security", "P0",
     "Two accounts, A with an item in its cart",
     "1. As user A, add a product and note the line id\n2. As user B — or with no session at all — call POST /deleteitem with A's line id\n3. Read A's cart",
     "{id: '<user A line id>'}",
     "Expected: the request is rejected and A's cart is unchanged. Actual: the line is deleted. /deleteitem takes only a line id — no token, no ownership check — so anyone who can guess or observe an id can empty a stranger's basket. Raised as DEMO-16",
     "tests/api/cart.api.spec.ts › does not let anyone delete another account's cart line", "DEMO-16"),

    ("CRT-055", "Invalid input", "Product id that does not exist is rejected", "Negative", "P1",
     "User is logged in",
     "1. Call POST /addtocart with prod_id 99999\n2. Read the cart\n3. Open the Cart page",
     "{prod_id: 99999}",
     "Expected: rejected as an unknown product. Actual: accepted, and the cart holds a line whose product /view reports as 'Not found.' — a row the UI cannot render and checkout still counts. Raised as DEMO-17",
     "tests/api/cart.api.spec.ts › rejects a product id that does not exist", "DEMO-17"),

    ("CRT-056", "Invalid input", "Negative product id is rejected", "Negative", "P2",
     "User is logged in",
     "1. Call POST /addtocart with prod_id -1\n2. Read the cart",
     "{prod_id: -1}",
     "Expected: rejected. Actual: accepted and stored. Same missing validation as CRT-055 with an obviously invalid value. Raised as DEMO-17",
     "tests/api/cart.api.spec.ts › rejects a negative product id", "DEMO-17"),

    ("CRT-057", "Invalid input", "Re-using a line item id does not overwrite an existing line", "Negative", "P1",
     "User is logged in with an empty cart",
     "1. Add product A with line id 'X'\n2. Add product B with the same line id 'X'\n3. Read the cart",
     "line id 'X' used twice",
     "Expected: two lines, or the second add rejected. Actual: one line — the second silently replaced the first. Line ids are client-generated and uniqueness is never enforced. Raised as DEMO-18",
     "tests/api/cart.api.spec.ts › does not silently overwrite a line when an id is reused", "DEMO-18"),

    ("CRT-058", "Error handling", "Cart page degrades gracefully when a line references a missing product", "Negative", "P1",
     "A cart containing a line whose prod_id does not exist (see CRT-055)",
     "1. Seed a cart line with prod_id 99999\n2. Open the Cart page\n3. Observe the table and the total",
     "{prod_id: 99999}",
     "The page should either omit the line with a clear message or show a placeholder — it must not render a blank row, throw in the console, or leave the total inconsistent with the rows shown",
     "", "DEMO-17"),

    ("CRT-059", "Invalid input", "Checkout is blocked or safe when the cart holds an unrenderable line", "Negative", "P1",
     "A cart containing a phantom line (CRT-055)",
     "1. Seed a phantom line\n2. Open the Cart page and click 'Place Order'\n3. Complete and submit the form",
     "{prod_id: 99999} + valid order details",
     "The receipt total must agree with what the customer was shown, and the order must not contain an item that cannot be fulfilled",
     "", "DEMO-17"),
]

DEFECTS = [
    ("DEMO-1", "Checkout", "Medium", "Low", "Open",
     "Receipt date is one month early",
     "The receipt is built with Date.getMonth(), which is zero-indexed, so every order confirmation is dated one month in the past.",
     "CRT-044", "tests/ui/cart/place-order.spec.ts › receipt shows the correct calendar month @bug"),
    ("DEMO-2", "API", "High", "Medium", "Open",
     "POST /login returns HTTP 500 with an HTML body for an empty username",
     "An empty username is not validated server-side; the endpoint raises and returns an HTML error page. Any client calling response.json() receives an opaque SyntaxError instead of a handled rejection.",
     "LGN-025", "tests/api/auth.api.spec.ts › rejects a login with an empty username @bug"),
    ("DEMO-3", "Checkout", "High", "Medium", "Open",
     "An empty cart can be checked out for 0 USD",
     "Placing an order with no items in the cart succeeds and issues a real order id for a zero amount. Creates junk orders and a fulfilment ambiguity.",
     "CRT-039", "tests/ui/cart/place-order.spec.ts › accepts an order for an empty cart at zero value"),
    ("DEMO-4", "Checkout", "Medium", "High", "Open",
     "Order validation is presence-only",
     "Name and Credit card are checked for a non-empty string only. Whitespace-only names and non-numeric card numbers are accepted, and expiry values are never range-checked.",
     "CRT-037, CRT-038, CRT-040", "tests/ui/cart/place-order.spec.ts › accepts a whitespace-only name / accepts a non-numeric credit card"),
    ("DEMO-5", "Security", "Medium", "High", "Open",
     "Login error wording allows username enumeration",
     "'Wrong password.' and 'User does not exist.' are distinguishable, letting an attacker confirm which usernames are registered before attempting credentials.",
     "LGN-031", "tests/ui/login/login.negative.spec.ts › does not leak whether an account exists"),
    ("DEMO-6", "Cart", "Low", "Medium", "Open",
     "Anonymous cart is discarded on login rather than merged",
     "Items added while logged out are silently lost when the user authenticates, so a customer who signs in to check out loses their basket.",
     "CRT-008", "tests/ui/cart/add-to-cart.spec.ts › does not carry an anonymous cart into the session after login"),
    ("DEMO-7", "Frontend", "Low", "Low", "Open",
     "Duplicate DOM ids on the category links",
     "The Phones, Laptops and Monitors links all use id='itemc'. Invalid HTML; breaks any id-based selector and assistive technology that relies on unique ids.",
     "CRT-049", "Locator strategy in src/pages/home.page.ts"),
    ("DEMO-8", "Data", "Low", "Low", "Open",
     "Product title contains a trailing newline",
     "The catalogue returns 'Sony vaio i7\\n'. Leaks into search, display and any exact-match comparison.",
     "CRT-050", "Trimmed comparison in src/api/demoblaze.client.ts"),
    ("DEMO-9", "Frontend", "Low", "Low", "Open",
     "Inconsistent add-to-cart confirmation text",
     "'Product added.' when logged in versus 'Product added' when logged out — two code paths with diverging copy.",
     "CRT-007", "tests/ui/cart/add-to-cart.spec.ts › does not carry an anonymous cart into the session after login"),
    ("DEMO-10", "Login", "Low", "High", "Open",
     "Enter key does not submit the login form",
     "The login modal binds no submit handler to the Enter key, so keyboard users must reach for the mouse.",
     "LGN-016", "Manual"),
    ("DEMO-11", "Security", "High", "Medium", "Open",
     "No rate limiting or lockout on failed logins",
     "Unlimited consecutive failed attempts are accepted with no delay, CAPTCHA or lockout, leaving accounts open to credential stuffing and brute force.",
     "LGN-032", "Manual"),
    ("DEMO-12", "Security", "Medium", "Medium", "Open",
     "No password policy",
     "Single-character passwords are accepted at registration; there is no minimum length, complexity or breach check.",
     "LGN-036", "Manual"),
    ("DEMO-13", "Login", "Medium", "Low", "Open",
     "Login failure is silent when the API is unreachable",
     "A failed request produces no user-facing feedback — the modal simply stays open, indistinguishable from an unclicked button.",
     "LGN-043", "Manual"),
    ("DEMO-14", "Security", "High", "High", "Open",
     "Full card number displayed unmasked on the receipt",
     "The order confirmation echoes the complete PAN as typed. Unnecessary exposure of cardholder data and a PCI-DSS concern in any real deployment.",
     "CRT-027", "tests/ui/cart/place-order.spec.ts › completes an order and reports the correct receipt"),
    ("DEMO-16", "Security", "High", "High", "Open",
     "Broken access control: any caller can delete any cart line",
     "POST /deleteitem takes only a line id — no auth token and no ownership check. An unauthenticated caller who knows or guesses a line id can delete items from a stranger's cart. OWASP A01. Made worse by DEMO-18, since line ids are client-generated and may follow a guessable scheme.",
     "CRT-054", "tests/api/cart.api.spec.ts › does not let anyone delete another account's cart line"),
    ("DEMO-17", "Cart", "Medium", "Medium", "Open",
     "Product id is not validated when adding to the cart",
     "POST /addtocart accepts any prod_id, including 99999 and -1. The resulting line references a product that /view reports as 'Not found.', leaving a row the UI cannot render while the cart still counts it.",
     "CRT-055, CRT-056, CRT-058, CRT-059", "tests/api/cart.api.spec.ts › rejects a product id that does not exist"),
    ("DEMO-18", "Cart", "Medium", "Medium", "Open",
     "Cart line ids are client-generated and not checked for uniqueness",
     "Re-using a line id on POST /addtocart silently replaces the existing line rather than adding a second or rejecting the request. Two tabs, or any client with a weak id scheme, can destroy each other's basket entries.",
     "CRT-057", "tests/api/cart.api.spec.ts › does not silently overwrite a line when an id is reused"),
    ("DEMO-15", "Checkout", "High", "Low", "Open",
     "Order confirmation is shown before the server confirms",
     "The receipt is rendered client-side without waiting for a successful server response, so a customer can be told an order succeeded when it did not.",
     "CRT-048", "Manual"),
]
